// export function itemModel() {
//     return {
//       name: "",
//       description: "",
//       createdAt: Date.now(),
//       updatedAt: null,
//     };
//   }

export function itemModel() {
  return {
    gid: '',
    c_gid: '',
    c_etat_valid: '',
    c_nom: '',
    c_x_coor2: '',
    c_y_coor2: '',
    c_lat_coor1: '',
    c_long_coor1: '',
    c_xy_precis: '',
    c_id_adr: '',
    c_adr_num: '',
    c_adr_voie: '',
    c_com_cp: '',
    c_com_insee: '',
    c_com_nom: '',
    c_acc: '',
    c_acc_lib: '',
    c_acc_pcsec: '',
    c_acc_acc: '',
    c_acc_etg: '',
    c_acc_complt: '',
    c_photo1: '',
    c_photo2: '',
    c_disp_j: '',
    c_disp_h: '',
    c_disp_complt: '',
    c_date_instal: '',
    c_etat_fonct: '',
    c_id_euro: '',
    c_lc_ped: '',
    c_dtpr_lcped: '',
    c_dtpr_lcad: '',
    c_dtpr_bat: '',
    c_freq_mnt: '',
    c_dispsurv: '',
    c_dermnt: '',
    c_maj_don: '',
    c_expt_siren: '',
    c_expt_rais: '',
    c_etat: '',
    c_application_provenance: '',
    c_doublon: '',
    c__edit_datemaj: '',
    c_srid_origin: '',
    the_geom: '',
    cc_photo1: '',
    __1: '',
  }
}
